### ISSUE TITLE
Document how to connect to a testnet

### ISSUE THREAD

**Issue by bgravenorst** [PegaSysEng/doc.teku#10]

**Comment by bgravenorst** [comment]
Additionally discuss how to connect a beacon chain node without any validators.
And mention the `--eth1-enabled` and `--initial-state` options

**Comment by q9f** [comment]
happy to take this unless someone else is already writing it

**Comment by MadelineMurray** [comment]
hi @q9f - that would be great.  If you need information from us, either tag us on there or you'll find us over on the Teku gitter (where I see you're already involved :-)).
