### ISSUE TITLE
Update documentation for Altona testnet

### ISSUE THREAD

**Issue by bgravenorst** [PegaSysEng/doc.teku#106]
Altona is now the default named network.

Additionally, remove the notes about using the 0.12.1-integration branch.

**Comment by MadelineMurray** [comment]
Does the Onyx testnet need adding as well? See this PR: https://github.com/PegaSysEng/teku/pull/2110

**Comment by ajsutton** [comment]
You can use Teku on Onyx testnet but I'd be pushing users towards the Altona testnet generally.
