### ISSUE TITLE
Page footer needs updating

### ISSUE THREAD

**Issue by benjaminion** [PegaSysEng/doc.teku#129]
The page footer currently says

> Questions or feedback? You can discuss [issues](https://github.com/PegaSysEng/doc.teku/issues) and obtain free support on [Teku Gitter channel](https://gitter.im/PegaSysEng/Teku).

Two issues:
  1. The first link should probably go to https://github.com/PegaSysEng/teku/issues
  2. The second link should now go to the Teku channel on the ConsenSys Discord. I'd make the change myself, but I haven't yet found a non-nasty way to link to Discord channels.

**Comment by MadelineMurray** [comment]
@bgravenorst  I think we might have either fixed point 2 in the latest version or have a PR up for it.  We might need to release/tag the Teku docs so it shows on the stable version. 

@benjaminion - I've been linking to the invite link that doesn't expire.  That's the best option I've found so far.
